### ISSUE TITLE
Add Code Blocks to indicate needed secondary libraries

### ISSUE THREAD

**Issue by jimbolive** [bsatrom/Adafruit_Seesaw#1]
I needed to add Adafruit-ST7735(contains Adafruit_mdGFX) to get the joy_wing_oled.ino example to compile.

It also needed a change in the example from #include Adafruit_GFX.h to #include Adafruit_mdGFX.h

I don't know if you're the right guy for this, but the Adafruit_ST7735 also doesn't support the 160x80 TFT featherwing resolution.

The example code is also a bit misleading, as the example name refers to OLED, but as far as I can tell the code is for the TFT...  Thx!!!

**Comment by bsatrom** [comment]
Thanks for filing the issue @jimbolive, I will take a look. In the meantime, which `ST7735` screen are you using?

**Comment by jimbolive** [comment]
Hi Brandon, 
I’m working with this one:
https://www.adafruit.com/product/3321
Jim

**Comment by bsatrom** [comment]
Thanks @jimbolive. I'll grab one of those for testing. Been on the road for meetings this week, but I'll take a look at this early next week. Thanks!

**Comment by rickkas7** [comment]
If you use the AdafruitColorTFTJoystickFeatherWing library in the community libraries, it will pull in all of the required dependencies automatically.

The basic and graphictest examples are included there and work out of the box.

More information here:
https://github.com/rickkas7/AdafruitColorTFTJoystickFeatherWing

**Comment by bsatrom** [comment]
Thanks @rickkas7! @jimbolive this should get you unblocked for now. I have one of these devices showing up today, and I'll get this issue resolved here once I do and have a chance to fix and test.
